"""Routing DSL and URL generation."""

from almasix.routing.resource import (
    PendingResourceRegistration,
    PendingSingletonRegistration,
    resource_verbs,
    set_resource_verbs,
)
from almasix.routing.router import (
    DuplicateRouteName,
    RedirectAction,
    Route,
    RouteDefinition,
    Router,
    ViewAction,
    WebSocketRouteDefinition,
    get_router,
    set_router,
)
from almasix.routing.signing import (
    has_valid_relative_signature,
    has_valid_signature,
    sign,
)
from almasix.routing.url import (
    MissingRouteParameter,
    RouteNotFound,
    UrlGenerator,
    action,
    asset,
    route,
    secure_asset,
    secure_url,
    signed_route,
    temporary_signed_route,
    to_action,
    to_route,
    url,
)

__all__ = [
    "DuplicateRouteName",
    "MissingRouteParameter",
    "PendingResourceRegistration",
    "PendingSingletonRegistration",
    "RedirectAction",
    "Route",
    "RouteDefinition",
    "RouteNotFound",
    "Router",
    "UrlGenerator",
    "ViewAction",
    "WebSocketRouteDefinition",
    "action",
    "asset",
    "get_router",
    "has_valid_relative_signature",
    "has_valid_signature",
    "resource_verbs",
    "route",
    "secure_asset",
    "secure_url",
    "set_resource_verbs",
    "set_router",
    "sign",
    "signed_route",
    "temporary_signed_route",
    "to_action",
    "to_route",
    "url",
]
